# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/therk/emb_sys_vivado/bram_assignment/bram_assignment.srcs/sources_1/bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_axi_bram_ctrl_0_0/UART_BRAM_Interfacing_axi_bram_ctrl_0_0.xci
# IP: The module: 'UART_BRAM_Interfacing_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/therk/emb_sys_vivado/bram_assignment/bram_assignment.gen/sources_1/bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_axi_bram_ctrl_0_0/UART_BRAM_Interfacing_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_BRAM_Interfacing_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/bram_assignment/bram_assignment.srcs/sources_1/bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_axi_bram_ctrl_0_0/UART_BRAM_Interfacing_axi_bram_ctrl_0_0.xci
# IP: The module: 'UART_BRAM_Interfacing_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/therk/emb_sys_vivado/bram_assignment/bram_assignment.gen/sources_1/bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_axi_bram_ctrl_0_0/UART_BRAM_Interfacing_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_BRAM_Interfacing_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
