# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/therk/emb_sys_vivado/constraints/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/UART_BRAM_Interfacing/UART_BRAM_Interfacing.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing || ORIG_REF_NAME==UART_BRAM_Interfacing} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_padder_0_0/UART_BRAM_Interfacing_padder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_padder_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_padder_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_clk_divider_0_0/UART_BRAM_Interfacing_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_clk_divider_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_clk_divider_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_rx_mod_0_0/UART_BRAM_Interfacing_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_rx_mod_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_rx_mod_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_axi_bram_ctrl_0_0/UART_BRAM_Interfacing_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_axi_bram_ctrl_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_processing_system7_0_0/UART_BRAM_Interfacing_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_processing_system7_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_processing_system7_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_proc_sys_reset_0_0/UART_BRAM_Interfacing_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_proc_sys_reset_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_blk_mem_gen_0_0_6/UART_BRAM_Interfacing_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_blk_mem_gen_0_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_xlconstant_0_1/UART_BRAM_Interfacing_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_xlconstant_0_1 || ORIG_REF_NAME==UART_BRAM_Interfacing_xlconstant_0_1} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_xlconstant_0_2/UART_BRAM_Interfacing_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_xlconstant_0_2 || ORIG_REF_NAME==UART_BRAM_Interfacing_xlconstant_0_2} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_xlconstant_1_0/UART_BRAM_Interfacing_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_xlconstant_1_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_xlconstant_1_0} -quiet] -quiet

# IP: bd/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_smartconnect_1_0/UART_BRAM_Interfacing_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_BRAM_Interfacing_smartconnect_1_0 || ORIG_REF_NAME==UART_BRAM_Interfacing_smartconnect_1_0} -quiet] -quiet

# XDC: /home/therk/emb_sys_vivado/bram_assignment/bram_assignment.gen/sources_1/bd/UART_BRAM_Interfacing/UART_BRAM_Interfacing_ooc.xdc
