# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/UART_to_PWM/UART_to_PWM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM || ORIG_REF_NAME==UART_to_PWM} -quiet] -quiet

# IP: bd/UART_to_PWM/ip/UART_to_PWM_clk_divider_0_0/UART_to_PWM_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM_clk_divider_0_0 || ORIG_REF_NAME==UART_to_PWM_clk_divider_0_0} -quiet] -quiet

# IP: bd/UART_to_PWM/ip/UART_to_PWM_rx_mod_0_0/UART_to_PWM_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM_rx_mod_0_0 || ORIG_REF_NAME==UART_to_PWM_rx_mod_0_0} -quiet] -quiet

# IP: bd/UART_to_PWM/ip/UART_to_PWM_xl_slice_0_0/UART_to_PWM_xl_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM_xl_slice_0_0 || ORIG_REF_NAME==UART_to_PWM_xl_slice_0_0} -quiet] -quiet

# IP: bd/UART_to_PWM/ip/UART_to_PWM_LUT_0_0/UART_to_PWM_LUT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM_LUT_0_0 || ORIG_REF_NAME==UART_to_PWM_LUT_0_0} -quiet] -quiet

# IP: bd/UART_to_PWM/ip/UART_to_PWM_counter_0_0/UART_to_PWM_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM_counter_0_0 || ORIG_REF_NAME==UART_to_PWM_counter_0_0} -quiet] -quiet

# IP: bd/UART_to_PWM/ip/UART_to_PWM_comparator_0_0/UART_to_PWM_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_to_PWM_comparator_0_0 || ORIG_REF_NAME==UART_to_PWM_comparator_0_0} -quiet] -quiet

# XDC: /home/therk/emb_sys_vivado/project_2/project_2.gen/sources_1/bd/UART_to_PWM/UART_to_PWM_ooc.xdc
