# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/PYNQ-Z2 v1.0.xdc

# Block Designs: /home/therk/emb_sys_vivado/blocks/UART2PWM/UART2PWM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM || ORIG_REF_NAME==UART2PWM} -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART2PWM/ip/UART2PWM_clk_divider_0_0/UART2PWM_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM_clk_divider_0_0 || ORIG_REF_NAME==UART2PWM_clk_divider_0_0} -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART2PWM/ip/UART2PWM_rx_mod_0_0/UART2PWM_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM_rx_mod_0_0 || ORIG_REF_NAME==UART2PWM_rx_mod_0_0} -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART2PWM/ip/UART2PWM_xl_slice_0_0/UART2PWM_xl_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM_xl_slice_0_0 || ORIG_REF_NAME==UART2PWM_xl_slice_0_0} -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART2PWM/ip/UART2PWM_LUT_0_0/UART2PWM_LUT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM_LUT_0_0 || ORIG_REF_NAME==UART2PWM_LUT_0_0} -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART2PWM/ip/UART2PWM_counter_0_0/UART2PWM_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM_counter_0_0 || ORIG_REF_NAME==UART2PWM_counter_0_0} -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART2PWM/ip/UART2PWM_comparator_0_0/UART2PWM_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART2PWM_comparator_0_0 || ORIG_REF_NAME==UART2PWM_comparator_0_0} -quiet] -quiet

# XDC: /home/therk/emb_sys_vivado/blocks/UART2PWM/UART2PWM_ooc.xdc
