# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/therk/emb_sys_vivado/blocks/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_blk_mem_gen_0_1/UART_BRAM_Interfacing_blk_mem_gen_0_1.xci
# IP: The module: 'UART_BRAM_Interfacing_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/therk/emb_sys_vivado/blocks/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_blk_mem_gen_0_1/UART_BRAM_Interfacing_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_BRAM_Interfacing_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/therk/emb_sys_vivado/blocks/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_blk_mem_gen_0_1/UART_BRAM_Interfacing_blk_mem_gen_0_1.xci
# IP: The module: 'UART_BRAM_Interfacing_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/therk/emb_sys_vivado/blocks/UART_BRAM_Interfacing/ip/UART_BRAM_Interfacing_blk_mem_gen_0_1/UART_BRAM_Interfacing_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_BRAM_Interfacing_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
